version: "3.9"
services:
  config:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - broker
      - postgres
    command: sh -c "
      sleep 4 &&
      ./bin/notifi"
    environment:
      BROKERS: broker:9092
      PARTITIONS: 100
      DSN: postgres://postgres:password@postgres:5432/notifi
      REQUEST_TOPIC: notifi-request
    ports:
      - "8080:8080"
      - "8081:8081"
  router:
    build:
      context: .
      dockerfile: Dockerfile.router
    depends_on:
      - broker
      - postgres
    command: sh -c "
      sleep 4 &&
      ./bin/router"
    environment:
      BROKERS: broker:9092
      DSN: postgres://postgres:password@postgres:5432/notifi
      REQUEST_TOPIC: notifi-request
      DELIVERY_TOPIC: notifi-delivery
  delivery:
    build:
      context: .
      dockerfile: Dockerfile.delivery
    depends_on:
      - broker
      - postgres
    command: sh -c "
      sleep 4 &&
      ./bin/delivery"
    environment:
      BROKERS: broker:9092
      DSN: postgres://postgres:password@postgres:5432/notifi
      DELIVERY_TOPIC: notifi-delivery
      FROM_NAME: notifi
      FROM_EMAIL: notifi@broswen.com
      SENDGRID_KEY: 123
      TWILIO_SID: abc
      TWILIO_TOKEN: 123
      FROM_NUMBER: 18005551234
      SKIP_DELIVERY: true
  poller:
    build:
      context: .
      dockerfile: Dockerfile.poller
    depends_on:
      - broker
      - postgres
    command: sh -c "
      sleep 4 &&
      ./bin/poller"
    environment:
      BROKERS: broker:9092
      DSN: postgres://postgres:password@postgres:5432/notifi
      DELIVERY_TOPIC: notifi-delivery
      POLL_INTERVAL: 1m
      PARTITION_START: 0
      PARTITION_END: 100
#TODO remove zookeeper and upgrade to kraft
  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    container_name: broker
    hostname: broker
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
  postgres:
    container_name: postgres
    hostname: postgres
    build:
      context: sql
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: notifi
    ports:
      - "5432:5432"