---
# Source: poller/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: poller
  namespace: notifi
  labels:
    helm.sh/chart: poller-0.1.0
    app.kubernetes.io/name: poller
    app.kubernetes.io/instance: poller
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  DSN: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEBwb3N0Z3Jlcy5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL25vdGlmaQ==
---
# Source: poller/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: poller
  namespace: notifi
  labels:
    helm.sh/chart: poller-0.1.0
    app.kubernetes.io/name: poller
    app.kubernetes.io/instance: poller
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  API_PORT: "8080"
  BROKERS: kafka-clusterip.kafka.svc.cluster.local:9092
  DELIVERY_TOPIC: notifi-delivery
  METRICS_PATH: /metrics
  METRICS_PORT: "8081"
  POLL_INTERVAL: 1m
---
# Source: poller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poller-0
  namespace: notifi
  labels:
    helm.sh/chart: poller-0.1.0
    app.kubernetes.io/name: poller
    app.kubernetes.io/instance: poller
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poller
      app.kubernetes.io/instance: poller
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: poller
        app.kubernetes.io/instance: poller
    spec:
      securityContext:
        {}
      containers:
        - name: poller-0
          securityContext:
            {}
          image: "broswen/notifi-poller:latest"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: poller
            - secretRef:
                name: poller
          env:
            - name: PARTITION_START
              value: "0"
            - name: PARTITION_END
              value: "50"
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: poller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poller-1
  namespace: notifi
  labels:
    helm.sh/chart: poller-0.1.0
    app.kubernetes.io/name: poller
    app.kubernetes.io/instance: poller
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poller
      app.kubernetes.io/instance: poller
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: poller
        app.kubernetes.io/instance: poller
    spec:
      securityContext:
        {}
      containers:
        - name: poller-1
          securityContext:
            {}
          image: "broswen/notifi-poller:latest"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: poller
            - secretRef:
                name: poller
          env:
            - name: PARTITION_START
              value: "50"
            - name: PARTITION_END
              value: "100"
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
