apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poller.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "poller.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.secret.data | nindent 2 }}